name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    strategy:
      max-parallel: 1
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      # - name: Check token
      #   shell: bash
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #   run: |
      #     if [ -z "$GH_TOKEN" ]; then
      #       echo "TOKEN VAZIO"
      #       exit 1
      #     fi
      #     echo "TOKEN PRESENTE"

      - name: Install dependencies
        run: npm ci

      - name: Build and publish (Windows)
        if: matrix.os == 'windows-latest'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run build:ts

          npx electron-builder --win --x64 --publish always

      # - name: Listar arquivos gerados (debug)
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     dir dist\

      - name: Build and publish (Mac)
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run build:ts
          npx electron-builder --mac --publish always
